language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps
  - make deps-test

script:
  - make test
